from typing import Any, Callable

class RingBuffer:
    _live: int
    _unfinished: int

    def __init__(
        self,
        maxsize: int,
        eviction_mode: int,
        dedup_mode: int,
        key_func: Callable[[Any], Any] | None,
    ) -> None: ...
    def put(self, item: object) -> int: ...
    def get(self) -> object: ...
    def peek(self) -> object: ...
    def qsize(self) -> int: ...
    def clear(self) -> None: ...
    def get_stats(self) -> dict[str, int]: ...
